Feature/product delivery
RovsingApplications/JSCustomComponents pull request #8
Opened 2020-11-24 11:22 UTC by dilshanmp7

Product delivery changes

2020-11-24 12:35 UTC, Omar-ABDELNABY commented on ProductDelivery/models/FTPType.ts
> +    FTP =0,
Please use tabs instead of spaces

2020-11-24 15:33 UTC, bondo11 commented on Framework/Utilities/ElementsCreator.ts
> +	static generateOverlayWithLoadingDots(width: number) {
space between functions

2020-11-24 15:33 UTC, bondo11 commented on Framework/Utilities/ElementsCreator.ts
> +	public static generateErrorBlock(errorText = 'Noget gik galt !') {
why the added space?

2020-11-24 16:14 UTC, Omar-ABDELNABY requested changes
Please check the comments, I know they may seem overwhelming, but most of them are repeated

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on Framework/Constants/Colors.ts
> +export default class Colors {
These are not referenced anywhere

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on Framework/Constants/Constants.ts
> +export default class Constants {
why moving these files outside the project??

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on Framework/Polyfills/ColorInputPolyfill.ts
> +// https://github.com/dciccale/nativeColorPicker
Why is this here as well??
A lot of Branding related files are here

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on Framework/Utilities/DomUtility.ts
> +		children.foreach(child => {
this is not used, but it's "forEach" BTW

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on ProductDelivery/src/Elements/CustomDeliveryResultElement.ts
> +import Colors from "../../../Framework/Constants/Colors";
unused import

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on ProductDelivery/src/Elements/CustomDeliveryResultElement.ts
> +    border: 10px solid white;
use tabs instead of spaces
indent

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on ProductDelivery/src/Elements/CustomDeliveryResultElement.ts
> +	position: absolute;
indent

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on ProductDelivery/src/ProductDeliveryWebElement.ts
>  	attributeChangedCallback(name: string, oldVal: string, newVal: string) {
add "observedAttributes" method like below:
private static get observedAttributes() {
		return ['api-key', 'api-url', 'language', 'creator-id'];
	}

2020-11-24 16:14 UTC, Omar-ABDELNABY commented on ProductDelivery/src/ProductDeliveryWebElement.ts
>  	attributeChangedCallback(name: string, oldVal: string, newVal: string) {
so when the attributes change the "attributeChangedCallback" will be invoked

2020-11-25 12:01 UTC, dilshanmp7 commented on Framework/Constants/Colors.ts
> +export default class Colors {
This is not related to product delivery , I haven't created that file in there.

2020-11-25 12:06 UTC, dilshanmp7 commented on Framework/Constants/Constants.ts
> +export default class Constants {
this also not related to product delivery.

2020-11-25 12:32 UTC, dilshanmp7 commented on ProductDelivery/demo/index.html
> +	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
yes but it does not work (the icon will not be shown)  when it encapsulated into web component.
https://medium.com/@ddamato/icon-font-within-web-components-5814788919c2

2020-11-25 12:40 UTC, dilshanmp7 commented on ProductDelivery/models/DeliveryResult.ts
> +import ProductDeliverySigner from "./ProductDeliverySigner";
No, they are not using outside, that makes sense to move it into the src folder.

2020-11-25 12:50 UTC, dilshanmp7 commented on ProductDelivery/models/Interpolation.ts
> +	public static InperpolationList: string[] = new Array(
I do not understand your comment in this context.

2020-11-26 08:47 UTC, dilshanmp7 commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +				document.dispatchEvent(showDataEvent);
this.dispatchEvent(showDataEvent);
does not work it generates an error as bellow
 CustomDeliveryEventTableElement.ts:161 Uncaught TypeError: this.dispatchEvent is not a function
    at Object.CustomDeliveryEventTableElement.runAction

2020-11-26 08:47 UTC, dilshanmp7 commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +		document.dispatchEvent(showSpinner);
this.dispatchEvent(showDataEvent);
does not work it generates an error  as above

2020-11-26 08:54 UTC, dilshanmp7 commented on ProductDelivery/src/ProductDeliveryWebElement.ts
> +		document.addEventListener('show-result', (evt) => this.showResult(evt as CustomEvent));
That does not work.

2020-11-26 08:55 UTC, dilshanmp7 commented on ProductDelivery/src/ProductDeliveryWebElement.ts
> +		border-color: #28BECE;
That makes sence.

2020-11-26 10:06 UTC, dilshanmp7 commented on ProductDelivery/src/ProductDeliveryWebElement.ts
> +		this.customDeliveryEventTableElement.updateDeliveryResultRowStatus(deliveryResult);
As you said above, inner component fires an event, and when it's triggered. the outer component calls a method in the inner component. but I am not sure can two inner components can communicate if they do not have references. Since parent component has references to both inner components I delegate it to parent component which is ProductDeliveryWebElement

2020-11-27 09:26 UTC, dilshanmp7 commented on ProductDelivery/src/ProductDeliveryWebElement.ts
> +	@import url("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css");
I have tried with SVG from font awesome, unfortunately, it did not work for me so I keep as it is.

2020-11-27 20:23 UTC, Omar-ABDELNABY commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +		document.dispatchEvent(showSpinner);
when calling it, use arrow function, or bind(this) instead of bind(deliveryResult) should fix the error

2020-11-27 21:11 UTC, Omar-ABDELNABY requested changes
please check the comments

2020-11-27 21:11 UTC, Omar-ABDELNABY commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +		document.dispatchEvent(showSpinner);
use arrow function when calling "runAction" or bind(this) instead of bind(deliveryResult)

2020-11-27 21:11 UTC, Omar-ABDELNABY commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +				document.dispatchEvent(showDataEvent);
use arrow function when calling "runAction" or bind(this) instead of bind(deliveryResult)

2020-11-27 21:11 UTC, Omar-ABDELNABY commented on ProductDelivery/src/Framework/Constants/Colors.ts
> +	public static readonly white = '#fff';
colors names should give them flexibility to change e.g. primary, secondary, warning, success
so they are not bound to a specific color

2020-11-27 21:11 UTC, Omar-ABDELNABY commented on ProductDelivery/src/ProductDeliveryWebElement.ts
> +import MakeRequest from "../../Branding/src/Framework/Utilities/MakeRequest";
Don't import from another component

2020-11-30 13:16 UTC, dilshanmp7 commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +				document.dispatchEvent(showDataEvent);
No, we cannot do that because I need get delivery ID pass into API when the button click if I bind this it bind the whole component.

2020-11-30 13:17 UTC, dilshanmp7 commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +		document.dispatchEvent(showSpinner);
No, we cannot do that because I need to get delivery ID pass into API when the button click if I bind this it binds the whole component. Then I cannot get the delivery ID

2020-11-30 17:48 UTC, dilshanmp7 commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +import MakeRequest from "../../../Branding/src/Framework/Utilities/MakeRequest";
yes that makes sense, I have copied "MakeRequest" into the component.

2020-12-01 19:07 UTC, dilshanmp7 commented on ProductDelivery/demo/index.html
> +	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
we do not have both only one we have v5 only.

2020-12-01 19:09 UTC, dilshanmp7 commented on ProductDelivery/demo/index.html
> +	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
we have only one font-awesome 5. maybe you forgot to pull.

2020-12-01 19:28 UTC, dilshanmp7 commented on ProductDelivery/productdelivery.html
> +<!DOCTYPE html>
yes, I have deleted this.

2020-12-01 19:36 UTC, dilshanmp7 commented on ProductDelivery/src/Elements/CustomDeliveryEventTableElement.ts
> +	background-color: Transparent;
This has been fixed already, pull the latest changes.

2020-12-01 20:45 UTC, dilshanmp7 commented on ProductDelivery/src/Framework/custom-element.decorator.ts
> +			if (config.useShadow) {
if it closed all custom child elements get null, so that does not work.

2020-12-07 11:39 UTC, merged